language: c
compiler:
  - gcc
  - clang
before_install:
  - sudo apt-get update
  - sudo apt-get install -y devscripts equivs
install:
  - sudo mk-build-deps --install --remove --tool 'apt-get --no-install-recommends -y' debian/control
  - sudo apt-get install --no-install-recommends -y libanyevent-perl libanyevent-i3-perl libextutils-pkgconfig-perl xcb-proto cpanminus xvfb xserver-xephyr xauth libinline-perl
  - sudo cpanm X11::XCB; sudo cpanm -n X11::XCB
script: make -j && (cd testcases && xvfb-run ./complete-run.pl)
