language: c
compiler:
  - gcc
  - clang
before_install:
  # The travis VMs run on Ubuntu 12.04 which is very old and a huge pain to get
  # into a state where we can build a recent version of i3 :(.
  - echo 'deb http://archive.ubuntu.com/ubuntu/ trusty main universe' | sudo tee /etc/apt/sources.list.d/trusty.list
  - echo 'APT::Default-Release "precise";' | sudo tee /etc/apt/apt.conf.d/default-release
  - echo -e "Package: libc6\nPin: release n=trusty\nPin-Priority: 999" | sudo tee /etc/apt/preferences.d/00-libc6
  - echo -e "Package: libxkbcommon*\nPin: release n=trusty\nPin-Priority: 999" | sudo tee /etc/apt/preferences.d/01-xkbcommon
  - echo -e "Package: libyajl*\nPin: release n=trusty\nPin-Priority: 999" | sudo tee /etc/apt/preferences.d/02-yajl
  - echo -e "Package: libxcb-image*\nPin: release n=trusty\nPin-Priority: 999" | sudo tee /etc/apt/preferences.d/03-xcb-image
  - sudo apt-get update
  - sudo apt-get install -t trusty libc6 libc6-dev
  - sudo apt-get install --no-install-recommends devscripts equivs
install:
  - sudo mk-build-deps --install --remove --tool 'apt-get --no-install-recommends' debian/control
  # Install as many dependencies as possible via apt because cpanm is not very reliable/easy to debug.
  - sudo apt-get install --no-install-recommends libanyevent-perl libanyevent-i3-perl libextutils-pkgconfig-perl xcb-proto cpanminus xvfb xserver-xephyr xauth libinline-perl libxml-simple-perl libmouse-perl libmousex-nativetraits-perl libextutils-depends-perl perl-modules libtest-deep-perl libtest-exception-perl libxml-parser-perl libtest-simple-perl libtest-fatal-perl libdata-dump-perl libtest-differences-perl libxml-tokeparser-perl libtest-use-ok-perl
  - sudo /bin/sh -c 'cpanm -n -v X11::XCB || true'
script: make -j && (cd testcases && xvfb-run ./complete-run.pl)
after_failure: cat /home/travis/.cpanm/build.log
